// Music Data with path and ids on src/musicData.ts

import { Song } from './types';  
export const songs: Song[] = [
  {
    id: '1000',
    title: 'Lost Soul',
    artist: 'NBSPLV',
    coverUrl: '/covers/cover1.jpeg',
    audioUrl: '/song1.mp3',
  },
  {
    id: '2000',
    title: 'Sajni',
    artist: 'Arijit Singh',
    coverUrl: '/covers/cover2.jpg',
    audioUrl: '/song2.mp3',
  },
  {
    id: '3000',
    title: 'Antariksh',
    artist: 'Anuv Jain',
    coverUrl: '/covers/cover3.jpeg',
    audioUrl: '/song3.mp3',
  },
  {
    id: '4000',
    title: 'Gul',
    artist: 'Anuv Jain',
    coverUrl: '/covers/cover4.jpg',
    audioUrl: '/song4.mp3',
  },
  {
    id: '5000',
    title: 'Husn',
    artist: 'Anuv Jain',
    coverUrl: '/covers/cover5.jpg',
    audioUrl: '/song5.mp3',
  },
  {
    id: '6000',
    title: 'Bakhuda Tumhi Ho',
    artist: 'Atif Aslam',
    coverUrl: '/covers/cover6.jpeg',
    audioUrl: '/song6.mp3',
  },
  {
    id: '7000',
    title: 'Amplifier',
    artist: 'Imran Khan',
    coverUrl: '/covers/cover7.jpeg',
    audioUrl: '/song7.mp3',
  },
  {
    id: '8000',
    title: 'Bewafa',
    artist: 'Imran Khan',
    coverUrl: '/covers/cover8.jpeg',
    audioUrl: '/song8.mp3',
  },
  {
    id: '9000',
    title: 'Free Fallin',
    artist: 'John Mayer',
    coverUrl: '/covers/cover9.jpeg',
    audioUrl: '/song9.mp3',
  },
  {
    id: '10000',
    title: 'Logical',
    artist: 'Olivia Rodrigo',
    coverUrl: '/covers/cover10.jpeg',
    audioUrl: '/song10.mp3',
  },
  {
    id: '11000',
    title: 'BIRDS OF A FEATHER',
    artist: 'Billie Eilish',
    coverUrl: '/covers/cover11.jpeg',
    audioUrl: '/song11.mp3',
  },
  {
    id: '12',
    title: 'Can’t Catch Me Now',
    artist: 'Olivia Rodrigo',
    coverUrl: '/covers/cover12.jpeg',
    audioUrl: '/song12.mp3',
  },

  {
    id: '13000',
    title: 'TV',
    artist: 'Billie Eilish',
    coverUrl: '/covers/cover13.jpeg',
    audioUrl: '/song13.mp3',
  },
  {
    id: '14000',
    title: 'Aayi Nai',
    artist: 'Sachin-Jigar',
    coverUrl: '/covers/cover14.jpeg',
    audioUrl: '/song14.mp3',
  },
  {
    id: '15000',
    title: 'All stars in the sky',
    artist: 'Coldplay',
    coverUrl: '/covers/cover15.png',
    audioUrl: '/song15.mp3',
  },
];
